### ISSUE TITLE
Multi language support

### ISSUE THREAD

**Issue by faizan-19** [techvootsolutions/flutter_text_detect_area#20]
Hi,
Do we have multi-language support in this package? 
or how we can achieve multi-language.
thanks

**Comment by tvtushar** [comment]
Hi @faizan-19 
We are also working on it, by providing parameter argument for passing value of intial TextRecognitionScript to set configuration of TextRecognizer like their is scripts as below

1.   Latin
2.   Chinese
3.   Devanagiri
4.   Japanese
5.   Korean
you can check languages by scripts
as per this document https://developers.google.com/ml-kit/vision/text-recognition/v2/languages
Thank you!

**Comment by tvPrincy** [comment]
Hello @faizan-19 Multi-language support add in latest release

**Comment by tvPrincy** [comment]
Hello @faizan-19 Multi-language support add in latest release
